/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/ContinuousDatum.h>
#import <TRChartsObjc/Support/Marshallers.hh>

@implementation TRContinuousDatum

-(TRContinuousDatum *)init
{
	self = [super init];
	if(self) {
		self.abscissa = 0.0;
	}
	return self;
}

+(TRContinuousDatum *)abscissa:(double)abscissa
{
	TRContinuousDatum * const result = [[TRContinuousDatum alloc] init];
	result.abscissa = abscissa;
	return result;
}

-(BOOL)isEqual:(id)anObject
{
	if(anObject == nil || ! [anObject isKindOfClass:[TRContinuousDatum class]]) {
		return NO;
	}
	TRContinuousDatum * other = anObject;
	BOOL result = YES;
	result = result && (self.abscissa == other.abscissa);
	return result;
}

-(NSUInteger)hash
{
	NSUInteger result = 7;
    result = 31 * result + (NSUInteger)self.abscissa;
	return result;
}

-(id)copyWithZone:(NSZone *)zone
{
	TRContinuousDatum * copy = [[self class] allocWithZone:zone];
	copy.abscissa = self.abscissa;
	return copy;
}

-(NSString*)description
{
	return [NSString stringWithFormat:@"TRContinuousDatum[%f]", self.abscissa];
}

@end