/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/DataScaleConstraintBehaviour.h>
#import <TRChartsObjc/Axis.h>
#import <TRChartsObjc/Chart.h>

#import <TRCharts/DataScaleConstraintBehaviour.hpp>
#import <TRCharts/Axis.hpp>
#import <TRCharts/Chart.hpp>

#import <TRChartsObjc/Support/Marshallers.hh>
#import <TRCodegenSupportObjc/Handle.hh>

@implementation TRDataScaleConstraintBehaviour

-(TRDataScaleConstraintBehaviour*)init {
	TRChartsObjc::verifyCurrentQueue();
	self = [super initConcrete];
	Charts::DataScaleConstraintBehaviour * const obj = new Charts::DataScaleConstraintBehaviour();
	CodegenSupportObjc::Handle * const handle = new CodegenSupportObjc::Handle(obj, self);
	obj->setHandle(handle);
	[self setHandle:handle];
	return self;
}

-(NSArray *)axes {
	TRChartsObjc::verifyCurrentQueue();
	CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([self handle]);
	std::shared_ptr<Charts::DataScaleConstraintBehaviour> obj = handle->getNativeObject<Charts::DataScaleConstraintBehaviour>();
	return TRChartsObjc::getListAxisMarshaller().unmarshall(obj->getAxes());
}

-(void)setAxes:(NSArray *)value {
	TRChartsObjc::verifyCurrentQueue();
	CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([self handle]);
	std::shared_ptr<Charts::DataScaleConstraintBehaviour> obj = handle->getNativeObject<Charts::DataScaleConstraintBehaviour>();
	obj->setAxes(TRChartsObjc::getListAxisMarshaller().marshall(value));
}

-(TRTransform *)apply:(TRChart *)chart size:(TRSize *)size transform:(TRTransform *)transform {
	TRChartsObjc::verifyCurrentQueue();
	CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([self handle]);
	std::shared_ptr<Charts::DataScaleConstraintBehaviour> obj = handle->getNativeObject<Charts::DataScaleConstraintBehaviour>();
	return TRChartsObjc::getTransformMarshaller().unmarshall(obj->apply(TRChartsObjc::getChartMarshaller().marshall(chart), TRChartsObjc::getSizeMarshaller().marshall(size), TRChartsObjc::getTransformMarshaller().marshall(transform)));	
}

@end