/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/DateInterval.h>
#import <TRChartsObjc/Support/Marshallers.hh>

@implementation TRDateInterval

-(TRDateInterval *)init
{
	self = [super init];
	if(self) {
		self.unit = TR_DATEUNIT_SECOND;
		self.magnitude = 0.0;
	}
	return self;
}

+(TRDateInterval *)unit:(TRDateUnit)unit magnitude:(double)magnitude
{
	TRDateInterval * const result = [[TRDateInterval alloc] init];
	result.unit = unit;
	result.magnitude = magnitude;
	return result;
}

-(BOOL)isEqual:(id)anObject
{
	if(anObject == nil || ! [anObject isKindOfClass:[TRDateInterval class]]) {
		return NO;
	}
	TRDateInterval * other = anObject;
	BOOL result = YES;
	result = result && (self.unit == other.unit);
	result = result && (self.magnitude == other.magnitude);
	return result;
}

-(NSUInteger)hash
{
	NSUInteger result = 7;
    result = 31 * result + (NSUInteger)self.unit;
    result = 31 * result + (NSUInteger)self.magnitude;
	return result;
}

-(id)copyWithZone:(NSZone *)zone
{
	TRDateInterval * copy = [[self class] allocWithZone:zone];
	copy.unit = self.unit;
	copy.magnitude = self.magnitude;
	return copy;
}

-(NSString*)description
{
	return [NSString stringWithFormat:@"TRDateInterval[%zd, %f]", self.unit, self.magnitude];
}

@end