/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/FixedRangeCalculator.h>

#import <TRCharts/FixedRangeCalculator.hpp>

#import <TRChartsObjc/Support/Marshallers.hh>
#import <TRCodegenSupportObjc/Handle.hh>

@implementation TRFixedRangeCalculator

-(TRFixedRangeCalculator*)init {
	TRChartsObjc::verifyCurrentQueue();
	self = [super initConcrete];
	Charts::FixedRangeCalculator * const obj = new Charts::FixedRangeCalculator();
	CodegenSupportObjc::Handle * const handle = new CodegenSupportObjc::Handle(obj, self);
	obj->setHandle(handle);
	[self setHandle:handle];
	return self;
}

-(TRRange *)range {
	TRChartsObjc::verifyCurrentQueue();
	CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([self handle]);
	std::shared_ptr<Charts::FixedRangeCalculator> obj = handle->getNativeObject<Charts::FixedRangeCalculator>();
	return TRChartsObjc::getRangeMarshaller().unmarshall(obj->getRange());
}

-(void)setRange:(TRRange *)value {
	TRChartsObjc::verifyCurrentQueue();
	CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([self handle]);
	std::shared_ptr<Charts::FixedRangeCalculator> obj = handle->getNativeObject<Charts::FixedRangeCalculator>();
	obj->setRange(TRChartsObjc::getRangeMarshaller().marshall(value));
}

-(TRRange *)calculateRange:(TRRange *)dataRange {
	TRChartsObjc::verifyCurrentQueue();
	CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([self handle]);
	std::shared_ptr<Charts::FixedRangeCalculator> obj = handle->getNativeObject<Charts::FixedRangeCalculator>();
	return TRChartsObjc::getRangeMarshaller().unmarshall(obj->calculateRange(TRChartsObjc::getRangeMarshaller().marshall(dataRange)));	
}

@end