/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/FixedDateTickCalculator.h>

#import <TRCharts/FixedDateTickCalculator.hpp>

#import <TRChartsObjc/Support/Marshallers.hh>
#import <TRCodegenSupportObjc/Handle.hh>

@implementation TRFixedDateTickCalculator

-(TRFixedDateTickCalculator*)init {
	TRChartsObjc::verifyCurrentQueue();
	self = [super initConcrete];
	Charts::FixedDateTickCalculator * const obj = new Charts::FixedDateTickCalculator();
	CodegenSupportObjc::Handle * const handle = new CodegenSupportObjc::Handle(obj, self);
	obj->setHandle(handle);
	[self setHandle:handle];
	return self;
}

-(TRDateInterval *)tickInterval {
	TRChartsObjc::verifyCurrentQueue();
	CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([self handle]);
	std::shared_ptr<Charts::FixedDateTickCalculator> obj = handle->getNativeObject<Charts::FixedDateTickCalculator>();
	return TRChartsObjc::getDateIntervalMarshaller().unmarshall(obj->getTickInterval());
}

-(void)setTickInterval:(TRDateInterval *)value {
	TRChartsObjc::verifyCurrentQueue();
	CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([self handle]);
	std::shared_ptr<Charts::FixedDateTickCalculator> obj = handle->getNativeObject<Charts::FixedDateTickCalculator>();
	obj->setTickInterval(TRChartsObjc::getDateIntervalMarshaller().marshall(value));
}

-(TRDateInterval *)calculateTickInterval:(TRRange *)dataRange visibleDataRange:(TRRange *)visibleDataRange screenLength:(double)screenLength {
	TRChartsObjc::verifyCurrentQueue();
	CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([self handle]);
	std::shared_ptr<Charts::FixedDateTickCalculator> obj = handle->getNativeObject<Charts::FixedDateTickCalculator>();
	return TRChartsObjc::getDateIntervalMarshaller().unmarshall(obj->calculateTickInterval(TRChartsObjc::getRangeMarshaller().marshall(dataRange), TRChartsObjc::getRangeMarshaller().marshall(visibleDataRange), TRChartsObjc::getNumberMarshaller().marshall(screenLength)));	
}

@end