/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#include <Foundation/Foundation.h>

/**
 * Formating mode (for dates/numbers)
 *
 */

typedef NS_ENUM(NSInteger, TRFormatSyntax)
{
	/**
	 * Use C standard library methods (default locale)
	 */
	TR_FORMATSYNTAX_CSTDLIB,

	/**
	 * Use platform methods (platform default locale)
	 */
	TR_FORMATSYNTAX_PLATFORM

};

typedef enum TRFormatSyntax TRFormatSyntax;

/**
 * Get the size (element count) of the TRFormatSyntax enum.
 *
 * @return The number of elements.
 */

static inline NSInteger TRFormatSyntax_size(void)
{
	return 2;
}

/**
 * Get the name of a given member of the TRFormatSyntax enum.
 *
 * @param value The enum value.
 * @return The name (as per source code), or "?" if an invalid value is provided.
 */

static inline NSString * TRFormatSyntax_name(TRFormatSyntax value)
{
	switch(value) {
	case TR_FORMATSYNTAX_CSTDLIB:
		return @"TR_FORMATSYNTAX_CSTDLIB";
	case TR_FORMATSYNTAX_PLATFORM:
		return @"TR_FORMATSYNTAX_PLATFORM";
	default:
		return @"?";
	}
}
