/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/Decoration.h>
#import <TRChartsObjc/LineStyle.h>
@class TRContinuousAxis;

/**
 * Draws a line at a fixed data position on a given axis
 *
 * @warning This is an automatically generated wrapper around a native object;
 * overriding methods will not work as expected.
 *
 */
@interface TRLineDecoration : TRDecoration

/** @name Fields */

/**
 * Axis to associate the decoration with. The decoration will intersect the axis
 * at the specified value
 *
 * @return The current axis.
 * @see setAxis:
 */
-(TRContinuousAxis *)axis;

/**
 * Axis to associate the decoration with. The decoration will intersect the axis
 * at the specified value
 *
 * @param value The new axis.
 * @see axis
 */
-(void)setAxis:(TRContinuousAxis *)value;

/**
 * Position in data co-ordinates (relative to the axis)
 *
 * @return The current value.
 * @see setValue:
 */
-(double)value;

/**
 * Position in data co-ordinates (relative to the axis)
 *
 * @param value The new value.
 * @see value
 */
-(void)setValue:(double)value;

/**
 * Drawing style for the line
 *
 * @return The current lineStyle.
 * @see setLineStyle:
 */
-(TRLineStyle *)lineStyle;

/**
 * Drawing style for the line
 *
 * @param value The new lineStyle.
 * @see lineStyle
 */
-(void)setLineStyle:(TRLineStyle *)value;

@end