/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/ContinuousSeries.h>
#import <TRChartsObjc/ScalarDatum.h>
#import <TRChartsObjc/LineStyle.h>
@protocol TRLineStyleSource;

/**
 * A series that displays scalar datums as a line.
 *
 * @warning This is an automatically generated wrapper around a native object;
 * overriding methods will not work as expected.
 *
 */
@interface TRLineSeries : TRContinuousSeries

/** @name Fields */

/**
 * The line style (may be overridden by values derived using the
 * lineStyleSource)
 *
 * @return The current line style.
 * @see setLineStyle:
 */
-(TRLineStyle *)lineStyle;

/**
 * The line style (may be overridden by values derived using the
 * lineStyleSource)
 *
 * @param value The new line style.
 * @see lineStyle
 */
-(void)setLineStyle:(TRLineStyle *)value;

/**
 * May optionally be provided, to control the per-datum line style.
 *
 * @see LineStyleSource
 *
 * @return The current line style source.
 * @see setLineStyleSource:
 */
-(id<TRLineStyleSource>)lineStyleSource;

/**
 * May optionally be provided, to control the per-datum line style.
 *
 * @see LineStyleSource
 *
 * @param value The new line style source.
 * @see lineStyleSource
 */
-(void)setLineStyleSource:(id<TRLineStyleSource>)value;

@end