/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#include <Foundation/Foundation.h>

#import <TRChartsObjc/ContinuousDatum.h>
#import <TRChartsObjc/OHLC.h>

/**
 * A continuous datum holding open/high/low/close values.
 *
 * @note This is a value class, when passing it to other library methods it is
 * always effectively copied.
 *
 */
@interface TROHLCDatum : TRContinuousDatum

/** @name Fields */
/**
 * The ordinate value.
 *
 * The dependent variable (usually)
 */
@property TROHLC * ordinate;

/** @name Methods */
/**
 * Default init.
 *
 * @return Initialized object.
 */
-(TROHLCDatum *)init;

/**
 * Create a OHLCDatum instance with provided values.
 *
 * @param abscissa The abscissa value.
 * @param ordinate The ordinate value.
 */
+(TROHLCDatum *)abscissa:(double)abscissa ordinate:(TROHLC *)ordinate;

/**
 * Test for equality (uses all struct fields)
 *
 * @param anObject Object to compare to.
 * @return True if the objects are equal.
 */
-(BOOL)isEqual:(id)anObject;

/**
 * Calculate the hash code (uses all struct fields)
 *
 * @return The hash code.
 */
-(NSUInteger)hash;

/**
 * Create a copy (uses all struct fields)
 *
 * @param zone Memory zone.
 * @return A copy.
 */
-(id)copyWithZone:(NSZone *)zone;

/**
 * Create a string description (uses all struct fields)
 *
 * @return The description.
 */
-(NSString*)description;

@end