/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/AbstractDateFormatter.h>
#import <TRChartsObjc/DateUnit.h>

/**
 * Format a date differently for the closest unit.
 *
 * @warning This is an automatically generated wrapper around a native object;
 * overriding methods will not work as expected.
 *
 */
@interface TRPerUnitDateFormatter : TRAbstractDateFormatter

/** @name Methods */

/**
 * Set the per-unit format string
 *
 * @param unit Relevant unit
 * @param format Format string (in either platform format or c-standard library format, depending on syntax parameter)
 */
-(void)setUnitFormat:(TRDateUnit)unit format:(NSString *)format;

/**
 * Get the per-unit format string (returns the empty string if no format set for
 * this unit)
 *
 * @param unit Relevant unit
 * @return The result.
 */
-(NSString *)getUnitFormat:(TRDateUnit)unit;

/**
 * Set the per-unit-zero format string (used when values below the unit are
 * zero)
 *
 * @param unit Relevant unit
 * @param format Format string (in either platform format or c-standard library format, depending on syntax parameter)
 */
-(void)setZeroUnitFormat:(TRDateUnit)unit format:(NSString *)format;

/**
 * Get the per-unit-zero format string (returns the empty string if no format
 * set for this unit)
 *
 * @param unit Relevant unit
 * @return The result.
 */
-(NSString *)getZeroUnitFormat:(TRDateUnit)unit;

@end