/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_BasicDateFormatter_hpp
#define Charts_BasicDateFormatter_hpp

#include <TRCharts/Common.hpp>
#include <TRCharts/AbstractDateFormatter.hpp>

namespace Charts
{
	
	class BasicDateFormatter;

	
	class GeneratedBasicDateFormatter : public Charts::AbstractDateFormatter
	{
	public:
		virtual ~GeneratedBasicDateFormatter(void);

		std::shared_ptr<BasicDateFormatter> getSharedPtr(void);

		std::shared_ptr<const BasicDateFormatter> getSharedPtr(void) const;

		virtual const std::string & getFormat(void) const = 0;

		virtual void setFormat(const std::string & value) = 0;

	protected:
		GeneratedBasicDateFormatter(void);

	};
}

#include <TRCharts/Impl/BasicDateFormatterImpl.hpp>

#endif