/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_BasicNumberFormatter_hpp
#define Charts_BasicNumberFormatter_hpp

#include <TRCharts/Common.hpp>
#include <TRCodegenSupport/BaseObject.hpp>
#include <TRCharts/NumberFormatter.hpp>

namespace Charts
{
	
	class BasicNumberFormatter;

	
	class GeneratedBasicNumberFormatter : public CodegenSupport::BaseObject, public Charts::NumberFormatter
	{
	public:
		virtual ~GeneratedBasicNumberFormatter(void);

		std::shared_ptr<BasicNumberFormatter> getSharedPtr(void);

		std::shared_ptr<const BasicNumberFormatter> getSharedPtr(void) const;

		virtual long getDecimalPlaces(void) const = 0;

		virtual void setDecimalPlaces(long value) = 0;

		virtual std::string formatNumber(double value) const = 0;

	protected:
		GeneratedBasicNumberFormatter(void);

	};
}

#include <TRCharts/Impl/BasicNumberFormatterImpl.hpp>

#endif