/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_Charts_cpp
#define Charts_Charts_cpp

#include <TRCharts/Charts.hpp>
#include <TRCharts/Impl/ChartsImpl.hpp>

Charts::LogLevel Charts::getLogLevel(void)
{
	return Impl::getLogLevel();
}

void Charts::setLogLevel(Charts::LogLevel value)
{
	Impl::setLogLevel(value);
}

const std::shared_ptr<Charts::LogHandler> & Charts::getLogHandler(void)
{
	return Impl::getLogHandler();
}

void Charts::setLogHandler(const std::shared_ptr<Charts::LogHandler> & value)
{
	Impl::setLogHandler(value);
}

bool Charts::isDebugGLValidationEnabled(void)
{
	return Impl::isDebugGLValidationEnabled();
}

void Charts::setDebugGLValidationEnabled(bool value)
{
	Impl::setDebugGLValidationEnabled(value);
}

#endif