/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_ConstraintBehaviour_hpp
#define Charts_ConstraintBehaviour_hpp

#include <TRCharts/Common.hpp>
#include <TRCharts/Transform.hpp>
#include <TRCharts/Size.hpp>

namespace Charts
{
	class Chart;

	
	class ConstraintBehaviour
	{
	public:
		virtual ~ConstraintBehaviour(void);

		virtual Charts::Transform apply(const std::shared_ptr<Charts::Chart> & chart, const Charts::Size & size, const Charts::Transform & transform) const = 0;

	};
}

#endif