/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_ContinuousAxis_hpp
#define Charts_ContinuousAxis_hpp

#include <TRCharts/Common.hpp>
#include <TRCharts/Axis.hpp>
#include <TRCharts/DataTransform.hpp>
#include <TRCharts/Range.hpp>

namespace Charts
{
	
	class ContinuousAxis;
	class AxisLayout;
	class RangeCalculator;

	
	class GeneratedContinuousAxis : public Charts::Axis
	{
	public:
		virtual ~GeneratedContinuousAxis(void);

		std::shared_ptr<ContinuousAxis> getSharedPtr(void);

		std::shared_ptr<const ContinuousAxis> getSharedPtr(void) const;

		virtual const std::shared_ptr<Charts::AxisLayout> & getLayout(void) const = 0;

		virtual void setLayout(const std::shared_ptr<Charts::AxisLayout> & value) = 0;

		virtual const std::shared_ptr<Charts::RangeCalculator> & getRangeCalculator(void) const = 0;

		virtual void setRangeCalculator(const std::shared_ptr<Charts::RangeCalculator> & value) = 0;

		virtual const Charts::DataTransform & getValueTransform(void) const = 0;

		virtual void setValueTransform(const Charts::DataTransform & value) = 0;

		virtual const Charts::Range & getDataRange(void) const = 0;

		virtual const Charts::Range & getScreenDataRange(void) const = 0;

	protected:
		GeneratedContinuousAxis(void);

	};
}

#include <TRCharts/Impl/ContinuousAxisImpl.hpp>

#endif