/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_ContinuousDataSource_hpp
#define Charts_ContinuousDataSource_hpp

#include <TRCharts/Common.hpp>
#include <TRCharts/IndexRange.hpp>

namespace Charts
{
	template <typename T> class ContinuousSeries;

	template <typename T>
	class ContinuousDataSource
	{
	public:
		virtual ~ContinuousDataSource(void);

		virtual Charts::IndexRange getDatumRange(const std::shared_ptr<Charts::ContinuousSeries<T>> & series) const = 0;

		virtual std::vector<T> getDatums(const std::shared_ptr<Charts::ContinuousSeries<T>> & series, const Charts::IndexRange & range) const = 0;

	};
}

#endif

#include <TRCharts/ContinuousDataSource.impl.hpp>