/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_DateUnit_hpp
#define Charts_DateUnit_hpp

#include <TRCharts/Common.hpp>

namespace Charts
{
	enum class DateUnit
	{
		Second,
		Minute,
		Hour,
		Day,
		Month,
		Year
	};

	namespace Enums
	{
		template <>
		inline size_t size<DateUnit>(void)
		{
			return 6;
		}

		template <>
		inline const char * name<DateUnit>(DateUnit value)
		{
			switch(value) {
			case DateUnit::Second:
				return "Second";
			case DateUnit::Minute:
				return "Minute";
			case DateUnit::Hour:
				return "Hour";
			case DateUnit::Day:
				return "Day";
			case DateUnit::Month:
				return "Month";
			case DateUnit::Year:
				return "Year";
			default:
				return "?";
			}
		}
	}

	inline std::ostream & operator<<(std::ostream & to, const DateUnit & from)
	{
		to << std::string(Enums::name(from));
		return to;
	}

}

#endif