/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_Drawable_hpp
#define Charts_Drawable_hpp

#include <TRCharts/Common.hpp>
#include <TRCharts/Attachable.hpp>

namespace Charts
{
	
	class Drawable;

	
	class GeneratedDrawable : public Charts::Attachable
	{
	public:
		virtual ~GeneratedDrawable(void);

		std::shared_ptr<Drawable> getSharedPtr(void);

		std::shared_ptr<const Drawable> getSharedPtr(void) const;

		virtual bool isVisible(void) const = 0;

		virtual void setVisible(bool value) = 0;

		virtual double getOpacity(void) const = 0;

		virtual void setOpacity(double value) = 0;

	protected:
		GeneratedDrawable(void);

	};
}

#include <TRCharts/Impl/DrawableImpl.hpp>

#endif