/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#include <TRCharts/Margin.hpp>
#include <TRCharts/Margin.hpp>


Charts::GeneratedMargin::GeneratedMargin(void)
	:left(0.0), right(0.0), bottom(0.0), top(0.0)
{
}


Charts::GeneratedMargin::GeneratedMargin(double left, double right, double bottom, double top)
	:left(left), right(right), bottom(bottom), top(top)
{
}


bool Charts::GeneratedMargin::operator==(const GeneratedMargin & other) const
{
	bool result = true;
	result = result && (this->left == other.left);
	result = result && (this->right == other.right);
	result = result && (this->bottom == other.bottom);
	result = result && (this->top == other.top);
	return result;
}


bool Charts::GeneratedMargin::operator!=(const GeneratedMargin & other) const
{
	return !(*this == other);
}


std::ostream & Charts::operator<<(std::ostream & to, const GeneratedMargin & from)
{
	to << "Margin[";
	to << "left: " << from.left << ", ";
	to << "right: " << from.right << ", ";
	to << "bottom: " << from.bottom << ", ";
	to << "top: " << from.top;
	to << "]";
	return to;
}