/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_NumberAxis_hpp
#define Charts_NumberAxis_hpp

#include <TRCharts/Common.hpp>
#include <TRCharts/AbstractNumberAxis.hpp>

namespace Charts
{
	
	class NumberAxis;
	class NumberTickCalculator;

	
	class GeneratedNumberAxis : public Charts::AbstractNumberAxis
	{
	public:
		virtual ~GeneratedNumberAxis(void);

		std::shared_ptr<NumberAxis> getSharedPtr(void);

		std::shared_ptr<const NumberAxis> getSharedPtr(void) const;

		virtual const std::shared_ptr<Charts::NumberTickCalculator> & getTickCalculator(void) const = 0;

		virtual void setTickCalculator(const std::shared_ptr<Charts::NumberTickCalculator> & value) = 0;

		virtual double getTickInterval(void) const = 0;

	protected:
		GeneratedNumberAxis(void);

	};
}

#include <TRCharts/Impl/NumberAxisImpl.hpp>

#endif