/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_PerUnitDateFormatter_cpp
#define Charts_PerUnitDateFormatter_cpp

#include <TRCharts/PerUnitDateFormatter.hpp>


Charts::GeneratedPerUnitDateFormatter::GeneratedPerUnitDateFormatter(void)
{
}


Charts::GeneratedPerUnitDateFormatter::~GeneratedPerUnitDateFormatter(void)
{
}


std::shared_ptr<Charts::PerUnitDateFormatter> Charts::GeneratedPerUnitDateFormatter::getSharedPtr(void)
{
	return std::dynamic_pointer_cast<Charts::PerUnitDateFormatter>(shared_from_this());
}


std::shared_ptr<const Charts::PerUnitDateFormatter> Charts::GeneratedPerUnitDateFormatter::getSharedPtr(void) const
{
	return std::dynamic_pointer_cast<const Charts::PerUnitDateFormatter>(shared_from_this());
}

#endif