/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef Charts_PointDecoration_hpp
#define Charts_PointDecoration_hpp

#include <TRCharts/Common.hpp>
#include <TRCharts/Decoration.hpp>
#include <TRCharts/Coordinates.hpp>
#include <TRCharts/PointStyle.hpp>

namespace Charts
{
	
	class PointDecoration;
	class ContinuousAxis;

	
	class GeneratedPointDecoration : public Charts::Decoration
	{
	public:
		virtual ~GeneratedPointDecoration(void);

		std::shared_ptr<PointDecoration> getSharedPtr(void);

		std::shared_ptr<const PointDecoration> getSharedPtr(void) const;

		virtual const std::shared_ptr<Charts::ContinuousAxis> & getAbscissaAxis(void) const = 0;

		virtual void setAbscissaAxis(const std::shared_ptr<Charts::ContinuousAxis> & value) = 0;

		virtual const std::shared_ptr<Charts::ContinuousAxis> & getOrdinateAxis(void) const = 0;

		virtual void setOrdinateAxis(const std::shared_ptr<Charts::ContinuousAxis> & value) = 0;

		virtual const Charts::Coordinates & getValue(void) const = 0;

		virtual void setValue(const Charts::Coordinates & value) = 0;

		virtual const Charts::PointStyle & getPointStyle(void) const = 0;

		virtual void setPointStyle(const Charts::PointStyle & value) = 0;

	protected:
		GeneratedPointDecoration(void);

	};
}

#include <TRCharts/Impl/PointDecorationImpl.hpp>

#endif