/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/Charts.h>

namespace TRChartsObjc
{
	BOOL getBooleanTestValue(BOOL defaultValue);

	double getNumberTestValue(double defaultValue);

	long getIntegerTestValue(long defaultValue);

	NSString * getStringTestValue(NSString * defaultValue);

	TRColor * getColorTestValue(TRColor * defaultValue);

	TRFont * getFontTestValue(TRFont * defaultValue);

	TRMargin * getMarginTestValue(TRMargin * defaultValue);

	TRSize * getSizeTestValue(TRSize * defaultValue);

	NSArray * getListStringTestValue(NSArray * defaultValue);

	TRFormatSyntax getFormatSyntaxTestValue(TRFormatSyntax defaultValue);

	TRDateUnit getDateUnitTestValue(TRDateUnit defaultValue);

	TRRange * getRangeTestValue(TRRange * defaultValue);

	NSArray * getListNumberTestValue(NSArray * defaultValue);

	TRDateInterval * getDateIntervalTestValue(TRDateInterval * defaultValue);

	id<TRRangeCalculator> getRangeCalculatorTestValue(id<TRRangeCalculator> defaultValue);

	TRDataTransform * getDataTransformTestValue(TRDataTransform * defaultValue);

	TRContinuousAxis * getContinuousAxisTestValue(TRContinuousAxis * defaultValue);

	TREdge getEdgeTestValue(TREdge defaultValue);

	TRLabel * getLabelTestValue(TRLabel * defaultValue);

	TRLineStyle * getLineStyleTestValue(TRLineStyle * defaultValue);

	id<TRAxisLayout> getAxisLayoutTestValue(id<TRAxisLayout> defaultValue);

	id<TRNumberFormatter> getNumberFormatterTestValue(id<TRNumberFormatter> defaultValue);

	id<TRNumberTickCalculator> getNumberTickCalculatorTestValue(id<TRNumberTickCalculator> defaultValue);

	id<TRDateFormatter> getDateFormatterTestValue(id<TRDateFormatter> defaultValue);

	id<TRDateTickCalculator> getDateTickCalculatorTestValue(id<TRDateTickCalculator> defaultValue);

	TRIndexRange * getIndexRangeTestValue(TRIndexRange * defaultValue);

	TRPointStyle * getPointStyleTestValue(TRPointStyle * defaultValue);

	id<TRContinuousDataSource> getContinuousDataSource_ScalarDatumTestValue(id<TRContinuousDataSource> defaultValue);

	TRScalarDatum * getScalarDatumTestValue(TRScalarDatum * defaultValue);

	id<TRLineStyleSource> getLineStyleSourceTestValue(id<TRLineStyleSource> defaultValue);

	id<TRContinuousDataSource> getContinuousDataSource_RangeDatumTestValue(id<TRContinuousDataSource> defaultValue);

	TRRangeDatum * getRangeDatumTestValue(TRRangeDatum * defaultValue);

	id<TRContinuousDataSource> getContinuousDataSource_OHLCDatumTestValue(id<TRContinuousDataSource> defaultValue);

	TROHLCDatum * getOHLCDatumTestValue(TROHLCDatum * defaultValue);

	TRCoordinates * getCoordinatesTestValue(TRCoordinates * defaultValue);

	NSArray * getListAnimationEffectTestValue(NSArray * defaultValue);

	id<TRAnimationEffect> getAnimationEffectTestValue(id<TRAnimationEffect> defaultValue);

	id<TRAnimationDelegate> getAnimationDelegateTestValue(id<TRAnimationDelegate> defaultValue);

	NSArray * getListDrawableTestValue(NSArray * defaultValue);

	TRDrawable * getDrawableTestValue(TRDrawable * defaultValue);

	id<TRConstraintBehaviour> getConstraintBehaviourTestValue(id<TRConstraintBehaviour> defaultValue);

	NSArray * getListAxisTestValue(NSArray * defaultValue);

	TRAxis * getAxisTestValue(TRAxis * defaultValue);

	TRTransform * getTransformTestValue(TRTransform * defaultValue);

	TRChart * getChartTestValue(TRChart * defaultValue);

	NSArray * getListEdgeTestValue(NSArray * defaultValue);

	NSArray * getListSeriesTestValue(NSArray * defaultValue);

	TRSeries * getSeriesTestValue(TRSeries * defaultValue);

	NSArray * getListDecorationTestValue(NSArray * defaultValue);

	TRDecoration * getDecorationTestValue(TRDecoration * defaultValue);

	NSArray * getListConstraintTestValue(NSArray * defaultValue);

	TRConstraint * getConstraintTestValue(TRConstraint * defaultValue);

	NSArray * getListAnimationTestValue(NSArray * defaultValue);

	TRAnimation * getAnimationTestValue(TRAnimation * defaultValue);

	NSArray * getListTouchTestValue(NSArray * defaultValue);

	TRTouch * getTouchTestValue(TRTouch * defaultValue);

	TRResizeMode getResizeModeTestValue(TRResizeMode defaultValue);

	TRPoint * getPointTestValue(TRPoint * defaultValue);

	TRFontHint getFontHintTestValue(TRFontHint defaultValue);

	TRLineMode getLineModeTestValue(TRLineMode defaultValue);

	TROHLC * getOHLCTestValue(TROHLC * defaultValue);

	TRLogLevel getLogLevelTestValue(TRLogLevel defaultValue);

	NSArray * getListColorTestValue(NSArray * defaultValue);

	NSArray * getListLineStyleTestValue(NSArray * defaultValue);

	id<TRColorSource> getColorSourceTestValue(id<TRColorSource> defaultValue);

	id<TRLogHandler> getLogHandlerTestValue(id<TRLogHandler> defaultValue);

}
