/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

package com.thomsonreuters.corptech.charts;

/**
 * Base for all autogenerated classes.
 */

public abstract class BaseObject
{
	private long handle;

	/**
	 * Prevent default construction (internal use only).
	 *
	 * @param dummy Ignored
	 */

	protected BaseObject(boolean dummy)
	{
	}

	/**
	 * Set the native object handle (internal use only).
	 *
	 * @param handle The native object handle.
	 */

	protected void setHandle(long handle)
	{
		this.handle = handle;
	}

	/**
	 * Get the native object handle (internal use only).
	 *
	 * @return The native object handle
	 */

	public long getHandle()
	{
		return handle;
	}

	/**
	 * Perform native cleanup (internal use only).
	 */

	protected abstract void onFinalize();

	/**
	 * Calls onFinalize (internal use only).
	 */

	protected void finalize()
	{
		onFinalize();
	}
}
