/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

package com.thomsonreuters.corptech.charts;

import java.util.List;

/**
 * <p>
 * Allows a constraint behaviour to be attached to a chart.
 * </p>
 * <p>
 * This approach is used because Attachable is a native-implemented class,
 * but the behaviour needs to be a host-provided callback.
 * </p>
 * <p>
 * <b>WARNING:</b> This is an automatically generated wrapper around a
 * native object; overriding methods will not work as expected.
 * </p>
 */

@SuppressWarnings("all")
public class Constraint extends Attachable
{
	/**
	 * Default constructor
	 */

	public Constraint()
	{
		this(true);
		setHandle(nativeCreate());
	}

	/**
	 * Get the behaviour.
	 * @return The current behaviour.
	 */

	public ConstraintBehaviour getBehaviour()
	{
		return (ConstraintBehaviour)nativeGetBehaviour(getHandle());
	}

	/**
	 * Set the behaviour.
	 * @param value The new behaviour.
	 */

	public void setBehaviour(final ConstraintBehaviour value)
	{
		nativeSetBehaviour(getHandle(), value);
	}

	// need this to prevent default constructor in base classes
	/*package*/ Constraint(boolean dummy)
	{
		super(dummy);
	}

	protected void onFinalize()
	{
		nativeDestroy(getHandle());
	}

	private final native long nativeCreate();
	private final native void nativeDestroy(long ptr);
	private final native Object nativeGetBehaviour(long ptr);
	private final native void nativeSetBehaviour(long ptr, Object value);
}
