/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

package com.thomsonreuters.corptech.charts;

import java.util.List;

/**
 * <p>
 * Formatter for dates
 * </p>
 */

@SuppressWarnings("all")
public interface DateFormatter
{
	/**
	 * <p>
	 * Format a date
	 * </p>
	 * @param seconds Seconds since midnight 1 Jan 1970 (unix stamp). Non-integer (subsecond) times are explicitly supported by the API, but may not be supported by all implementations.
	 * @param unit Unit hint, this is provided when formatting dates at a given tick interval, so the formatter can display different ranges of dates with varying precision.
	 * @return The result.
	 */

	String formatDate(double seconds, DateUnit unit);

}
