/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

package com.thomsonreuters.corptech.charts;

import java.util.List;

/**
 * <p>
 * Callback interface for calculating the tick interval for a date axis
 * </p>
 */

@SuppressWarnings("all")
public interface DateTickCalculator
{
	/**
	 * <p>
	 * Should return the date interval between ticks
	 * </p>
	 * @param dataRange Total data range for the axis
	 * @param visibleDataRange Data range that is visible under the current data transform
	 * @param screenLength Visual length of the axis on the screen (in points)
	 * @return The result.
	 */

	DateInterval calculateTickInterval(Range dataRange, Range visibleDataRange, double screenLength);

}
