/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

package com.thomsonreuters.corptech.charts;

import java.util.List;

/**
 * <p>
 * A range calculator that always returns a fixed range.
 * </p>
 * <p>
 * <b>WARNING:</b> This is an automatically generated wrapper around a
 * native object; overriding methods will not work as expected.
 * </p>
 */

@SuppressWarnings("all")
public class FixedRangeCalculator extends BaseObject implements RangeCalculator
{
	/**
	 * Default constructor
	 */

	public FixedRangeCalculator()
	{
		this(true);
		setHandle(nativeCreate());
	}

	/**
	 * Get the fixed range.
	 * @return The current fixed range.
	 */

	public Range getRange()
	{
		return (Range)nativeGetRange(getHandle());
	}

	/**
	 * Set the fixed range.
	 * @param value The new fixed range.
	 */

	public void setRange(final Range value)
	{
		nativeSetRange(getHandle(), value);
	}

	/**
	 * <p>
	 * The output data range is always the same as the value supplied in the
	 * range field
	 * </p>
	 * @param dataRange Input data range
	 * @return The result.
	 */

	public Range calculateRange(final Range dataRange)
	{
		return (Range)nativeCalculateRange(getHandle(), dataRange);
	}

	// need this to prevent default constructor in base classes
	/*package*/ FixedRangeCalculator(boolean dummy)
	{
		super(dummy);
	}

	protected void onFinalize()
	{
		nativeDestroy(getHandle());
	}

	private final native long nativeCreate();
	private final native void nativeDestroy(long ptr);
	private final native Object nativeGetRange(long ptr);
	private final native void nativeSetRange(long ptr, Object value);
	private final native Object nativeCalculateRange(long ptr, Object dataRange);
}
