/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

package com.thomsonreuters.corptech.charts;

/**
 * <p>
 * Log level, each log level implies that level, and all more severe levels
 * </p>
 */

public enum LogLevel
{
	/**
	 * <p>
	 * Log everything
	 * </p>
	 */

	TRACE,

	/**
	 * <p>
	 * Log internal developer information
	 * </p>
	 */

	DEBUG,

	/**
	 * <p>
	 * Log general information
	 * </p>
	 */

	INFO,

	/**
	 * <p>
	 * Log minor/recoverable errors and incorrect usage
	 * </p>
	 */

	WARN,

	/**
	 * <p>
	 * Log serious errors
	 * </p>
	 */

	ERROR

}
