/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

package com.thomsonreuters.corptech.charts;

import java.util.List;

/**
 * <p>
 * An axis that displays uniformly spaced (linear) number ticks.
 * </p>
 * <p>
 * <b>WARNING:</b> This is an automatically generated wrapper around a
 * native object; overriding methods will not work as expected.
 * </p>
 */

@SuppressWarnings("all")
public class NumberAxis extends AbstractNumberAxis
{
	/**
	 * Default constructor
	 */

	public NumberAxis()
	{
		this(true);
		setHandle(nativeCreate());
	}

	/**
	 * Get the tick calculator.
	 * @return The current tick calculator.
	 */

	public NumberTickCalculator getTickCalculator()
	{
		return (NumberTickCalculator)nativeGetTickCalculator(getHandle());
	}

	/**
	 * Set the tick calculator.
	 * @param value The new tick calculator.
	 */

	public void setTickCalculator(final NumberTickCalculator value)
	{
		nativeSetTickCalculator(getHandle(), value);
	}

	/**
	 * Get the tick interval.
	 * @return The current tick interval.
	 */

	public double getTickInterval()
	{
		return nativeGetTickInterval(getHandle());
	}

	// need this to prevent default constructor in base classes
	/*package*/ NumberAxis(boolean dummy)
	{
		super(dummy);
	}

	protected void onFinalize()
	{
		nativeDestroy(getHandle());
	}

	private final native long nativeCreate();
	private final native void nativeDestroy(long ptr);
	private final native Object nativeGetTickCalculator(long ptr);
	private final native void nativeSetTickCalculator(long ptr, Object value);
	private final native double nativeGetTickInterval(long ptr);
}
