/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

package com.thomsonreuters.corptech.charts;

import java.util.List;

/**
 * <p>
 * Represents a 2D size.
 * </p>
 * <p>
 * <b>NOTE:</b> This is a value class, when passing it to other library
 * methods it is always effectively copied.
 * </p>
 */

@SuppressWarnings("all")
public class Size
{
	private double width;
	private double height;

	/**
	 * Initialize a Size with default values.
	 */
	public Size()
	{
	}

	/**
	 * Initialize a Size with provided values.
	 *
	 * @param width The X dimension.
	 * @param height The Y dimension.
	 */

	public Size(double width, double height)
	{
		this.width = width;
		this.height = height;
	}

	/**
	 * Get the X dimension.
	 * @return The current X dimension.
	 */

	public final double getWidth()
	{
		return this.width;
	}

	/**
	 * Set the X dimension.
	 * @param value The new X dimension.
	 */

	public final void setWidth(final double value)
	{
		this.width = value;
	}

	/**
	 * Get the Y dimension.
	 * @return The current Y dimension.
	 */

	public final double getHeight()
	{
		return this.height;
	}

	/**
	 * Set the Y dimension.
	 * @param value The new Y dimension.
	 */

	public final void setHeight(final double value)
	{
		this.height = value;
	}

	@Override
	public String toString()
	{
		return "Size {" +
				"width=" + width + ", " +
				"height=" + height +
				"}";
	}

	@Override
	public boolean equals(final Object other)
	{
		if(this == other) return true;
		if(!(other instanceof Size)) return false;

		final Size tmp = (Size)other;

		if(!(this.width == tmp.width)) return false;
		if(!(this.height == tmp.height)) return false;

		return true;
	}

	@Override
	public int hashCode()
	{
		int result = 7;

		result = 31 * result + ((Double)width).hashCode();
		result = 31 * result + ((Double)height).hashCode();

		return result;
	}

}
