/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#include <TRChartsObjc/Support/AnimationDelegateInterfaceMarshaller.hh>
#include <TRChartsObjc/Support/Marshallers.hh>
#include <TRCodegenSupportObjc/Handle.hh>
#include <TRCodegenSupportObjc/BaseObject.h>


class TRChartsObjc::AnimationDelegateInterfaceMarshaller::Proxy : public Charts::AnimationDelegate
{
public:
	Proxy(const AnimationDelegateInterfaceMarshaller & marshaller, CodegenSupportObjc::StrongAnyPtr hostObject);

	virtual ~Proxy(void);

	CodegenSupportObjc::StrongAnyPtr getHostObject(void) const;

	virtual void animationCompleted(const std::shared_ptr<Charts::Animation> & animation) const;

	virtual void animationCancelled(const std::shared_ptr<Charts::Animation> & animation) const;

private:
	const AnimationDelegateInterfaceMarshaller & marshaller;
	mutable id __strong strongHostObject;
};



std::shared_ptr<Charts::AnimationDelegate> TRChartsObjc::AnimationDelegateInterfaceMarshaller::marshall(const CodegenSupportObjc::StrongAnyPtr & in) const
{
	if(in) {
		if([in isKindOfClass:[TRBaseObject class]]) {
			CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([in handle]);
			return handle->getNativeObject<Charts::AnimationDelegate>();
		} else {
			return std::make_shared<Proxy>(*this, in);
		}
	}
	return std::shared_ptr<Charts::AnimationDelegate>();
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::AnimationDelegateInterfaceMarshaller::unmarshall(const std::shared_ptr<Charts::AnimationDelegate> & in) const
{
	if(in) {
		CodegenSupport::BaseObject * const baseObject = dynamic_cast<CodegenSupport::BaseObject *>(in.get());
		if(baseObject) {
			CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>(baseObject->getHandle());
			return handle->getHostObject();
		} else {
			Proxy * proxy = dynamic_cast<Proxy *>(in.get());
			if(proxy) {
				return proxy->getHostObject();
			} else {
				throw std::logic_error("Cannot unmarshall");
			}
		}
	}
	return nullptr;
}


std::shared_ptr<Charts::AnimationDelegate> TRChartsObjc::AnimationDelegateInterfaceMarshaller::marshallBoxed(const id & in) const
{
	return marshall(in);
}


id TRChartsObjc::AnimationDelegateInterfaceMarshaller::unmarshallBoxed(const std::shared_ptr<Charts::AnimationDelegate> & in) const
{
	return unmarshall(in);
}

// TODO: temporary hack until we fix static init + threads problems properly

void TRChartsObjc::AnimationDelegateInterfaceMarshaller::init(void) const
{
}



TRChartsObjc::AnimationDelegateInterfaceMarshaller::Proxy::Proxy(const AnimationDelegateInterfaceMarshaller & marshaller, const CodegenSupportObjc::StrongAnyPtr hostObject)
	:marshaller(marshaller), strongHostObject(hostObject)
{
}


TRChartsObjc::AnimationDelegateInterfaceMarshaller::Proxy::~Proxy(void)
{
	// anything to verify here?
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::AnimationDelegateInterfaceMarshaller::Proxy::getHostObject(void) const
{
	return strongHostObject;
}


void TRChartsObjc::AnimationDelegateInterfaceMarshaller::Proxy::animationCompleted(const std::shared_ptr<Charts::Animation> & animation) const
{
	TRChartsObjc::verifyCurrentQueue();
	id<TRAnimationDelegate> target = getHostObject();
	[target animationCompleted:TRChartsObjc::getAnimationMarshaller().unmarshall(animation)];
}


void TRChartsObjc::AnimationDelegateInterfaceMarshaller::Proxy::animationCancelled(const std::shared_ptr<Charts::Animation> & animation) const
{
	TRChartsObjc::verifyCurrentQueue();
	id<TRAnimationDelegate> target = getHostObject();
	[target animationCancelled:TRChartsObjc::getAnimationMarshaller().unmarshall(animation)];
}

