/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#include <TRChartsObjc/Support/LineStyleSourceInterfaceMarshaller.hh>
#include <TRChartsObjc/Support/Marshallers.hh>
#include <TRCodegenSupportObjc/Handle.hh>
#include <TRCodegenSupportObjc/BaseObject.h>


class TRChartsObjc::LineStyleSourceInterfaceMarshaller::Proxy : public Charts::LineStyleSource
{
public:
	Proxy(const LineStyleSourceInterfaceMarshaller & marshaller, CodegenSupportObjc::StrongAnyPtr hostObject);

	virtual ~Proxy(void);

	CodegenSupportObjc::StrongAnyPtr getHostObject(void) const;

	virtual std::vector<Charts::LineStyle> getLineStyles(const std::shared_ptr<Charts::Series> & series, const Charts::IndexRange & range, const Charts::LineStyle & defaultLineStyle) const;

private:
	const LineStyleSourceInterfaceMarshaller & marshaller;
	mutable id __strong strongHostObject;
};



std::shared_ptr<Charts::LineStyleSource> TRChartsObjc::LineStyleSourceInterfaceMarshaller::marshall(const CodegenSupportObjc::StrongAnyPtr & in) const
{
	if(in) {
		if([in isKindOfClass:[TRBaseObject class]]) {
			CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([in handle]);
			return handle->getNativeObject<Charts::LineStyleSource>();
		} else {
			return std::make_shared<Proxy>(*this, in);
		}
	}
	return std::shared_ptr<Charts::LineStyleSource>();
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::LineStyleSourceInterfaceMarshaller::unmarshall(const std::shared_ptr<Charts::LineStyleSource> & in) const
{
	if(in) {
		CodegenSupport::BaseObject * const baseObject = dynamic_cast<CodegenSupport::BaseObject *>(in.get());
		if(baseObject) {
			CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>(baseObject->getHandle());
			return handle->getHostObject();
		} else {
			Proxy * proxy = dynamic_cast<Proxy *>(in.get());
			if(proxy) {
				return proxy->getHostObject();
			} else {
				throw std::logic_error("Cannot unmarshall");
			}
		}
	}
	return nullptr;
}


std::shared_ptr<Charts::LineStyleSource> TRChartsObjc::LineStyleSourceInterfaceMarshaller::marshallBoxed(const id & in) const
{
	return marshall(in);
}


id TRChartsObjc::LineStyleSourceInterfaceMarshaller::unmarshallBoxed(const std::shared_ptr<Charts::LineStyleSource> & in) const
{
	return unmarshall(in);
}

// TODO: temporary hack until we fix static init + threads problems properly

void TRChartsObjc::LineStyleSourceInterfaceMarshaller::init(void) const
{
}



TRChartsObjc::LineStyleSourceInterfaceMarshaller::Proxy::Proxy(const LineStyleSourceInterfaceMarshaller & marshaller, const CodegenSupportObjc::StrongAnyPtr hostObject)
	:marshaller(marshaller), strongHostObject(hostObject)
{
}


TRChartsObjc::LineStyleSourceInterfaceMarshaller::Proxy::~Proxy(void)
{
	// anything to verify here?
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::LineStyleSourceInterfaceMarshaller::Proxy::getHostObject(void) const
{
	return strongHostObject;
}


std::vector<Charts::LineStyle> TRChartsObjc::LineStyleSourceInterfaceMarshaller::Proxy::getLineStyles(const std::shared_ptr<Charts::Series> & series, const Charts::IndexRange & range, const Charts::LineStyle & defaultLineStyle) const
{
	TRChartsObjc::verifyCurrentQueue();
	id<TRLineStyleSource> target = getHostObject();
	return TRChartsObjc::getListLineStyleMarshaller().marshall([target getLineStyles:TRChartsObjc::getSeriesMarshaller().unmarshall(series) range:TRChartsObjc::getIndexRangeMarshaller().unmarshall(range) defaultLineStyle:TRChartsObjc::getLineStyleMarshaller().unmarshall(defaultLineStyle)]); 	
}

