/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#include <TRChartsObjc/Support/NumberTickCalculatorInterfaceMarshaller.hh>
#include <TRChartsObjc/Support/Marshallers.hh>
#include <TRCodegenSupportObjc/Handle.hh>
#include <TRCodegenSupportObjc/BaseObject.h>


class TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::Proxy : public Charts::NumberTickCalculator
{
public:
	Proxy(const NumberTickCalculatorInterfaceMarshaller & marshaller, CodegenSupportObjc::StrongAnyPtr hostObject);

	virtual ~Proxy(void);

	CodegenSupportObjc::StrongAnyPtr getHostObject(void) const;

	virtual double calculateTickInterval(const Charts::Range & dataRange, const Charts::Range & visibleDataRange, double screenLength) const;

private:
	const NumberTickCalculatorInterfaceMarshaller & marshaller;
	mutable id __strong strongHostObject;
};



std::shared_ptr<Charts::NumberTickCalculator> TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::marshall(const CodegenSupportObjc::StrongAnyPtr & in) const
{
	if(in) {
		if([in isKindOfClass:[TRBaseObject class]]) {
			CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>([in handle]);
			return handle->getNativeObject<Charts::NumberTickCalculator>();
		} else {
			return std::make_shared<Proxy>(*this, in);
		}
	}
	return std::shared_ptr<Charts::NumberTickCalculator>();
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::unmarshall(const std::shared_ptr<Charts::NumberTickCalculator> & in) const
{
	if(in) {
		CodegenSupport::BaseObject * const baseObject = dynamic_cast<CodegenSupport::BaseObject *>(in.get());
		if(baseObject) {
			CodegenSupportObjc::Handle * const handle = static_cast<CodegenSupportObjc::Handle *>(baseObject->getHandle());
			return handle->getHostObject();
		} else {
			Proxy * proxy = dynamic_cast<Proxy *>(in.get());
			if(proxy) {
				return proxy->getHostObject();
			} else {
				throw std::logic_error("Cannot unmarshall");
			}
		}
	}
	return nullptr;
}


std::shared_ptr<Charts::NumberTickCalculator> TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::marshallBoxed(const id & in) const
{
	return marshall(in);
}


id TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::unmarshallBoxed(const std::shared_ptr<Charts::NumberTickCalculator> & in) const
{
	return unmarshall(in);
}

// TODO: temporary hack until we fix static init + threads problems properly

void TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::init(void) const
{
}



TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::Proxy::Proxy(const NumberTickCalculatorInterfaceMarshaller & marshaller, const CodegenSupportObjc::StrongAnyPtr hostObject)
	:marshaller(marshaller), strongHostObject(hostObject)
{
}


TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::Proxy::~Proxy(void)
{
	// anything to verify here?
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::Proxy::getHostObject(void) const
{
	return strongHostObject;
}


double TRChartsObjc::NumberTickCalculatorInterfaceMarshaller::Proxy::calculateTickInterval(const Charts::Range & dataRange, const Charts::Range & visibleDataRange, double screenLength) const
{
	TRChartsObjc::verifyCurrentQueue();
	id<TRNumberTickCalculator> target = getHostObject();
	return TRChartsObjc::getNumberMarshaller().marshall([target calculateTickInterval:TRChartsObjc::getRangeMarshaller().unmarshall(dataRange) visibleDataRange:TRChartsObjc::getRangeMarshaller().unmarshall(visibleDataRange) screenLength:TRChartsObjc::getNumberMarshaller().unmarshall(screenLength)]); 	
}

