/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/Support/RangeStructMarshaller.hh>
#import <TRChartsObjc/Support/Marshallers.hh>



Charts::Range TRChartsObjc::RangeStructMarshaller::marshall(const CodegenSupportObjc::StrongAnyPtr & in) const
{
	TRRange * const tmp = (TRRange*)in;
	Charts::Range out;
	out.min = TRChartsObjc::getNumberMarshaller().marshall([tmp min]);
	out.max = TRChartsObjc::getNumberMarshaller().marshall([tmp max]);
	return out;
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::RangeStructMarshaller::unmarshall(const Charts::Range & in) const
{
	TRRange * out = [[TRRange alloc] init];
	[out setMin:TRChartsObjc::getNumberMarshaller().unmarshall(in.min)];
	[out setMax:TRChartsObjc::getNumberMarshaller().unmarshall(in.max)];
	return out;
}


Charts::Range TRChartsObjc::RangeStructMarshaller::marshallBoxed(const id & in) const
{
	return marshall(in);
}


id TRChartsObjc::RangeStructMarshaller::unmarshallBoxed(const Charts::Range & in) const
{
	return unmarshall(in);
}

// TODO: temporary hack until we fix static init + threads problems properly

void TRChartsObjc::RangeStructMarshaller::init(void) const
{
}

