/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/Support/SizeStructMarshaller.hh>
#import <TRChartsObjc/Support/Marshallers.hh>



Charts::Size TRChartsObjc::SizeStructMarshaller::marshall(const CodegenSupportObjc::StrongAnyPtr & in) const
{
	TRSize * const tmp = (TRSize*)in;
	Charts::Size out;
	out.width = TRChartsObjc::getNumberMarshaller().marshall([tmp width]);
	out.height = TRChartsObjc::getNumberMarshaller().marshall([tmp height]);
	return out;
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::SizeStructMarshaller::unmarshall(const Charts::Size & in) const
{
	TRSize * out = [[TRSize alloc] init];
	[out setWidth:TRChartsObjc::getNumberMarshaller().unmarshall(in.width)];
	[out setHeight:TRChartsObjc::getNumberMarshaller().unmarshall(in.height)];
	return out;
}


Charts::Size TRChartsObjc::SizeStructMarshaller::marshallBoxed(const id & in) const
{
	return marshall(in);
}


id TRChartsObjc::SizeStructMarshaller::unmarshallBoxed(const Charts::Size & in) const
{
	return unmarshall(in);
}

// TODO: temporary hack until we fix static init + threads problems properly

void TRChartsObjc::SizeStructMarshaller::init(void) const
{
}

