/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/Support/TouchStructMarshaller.hh>
#import <TRChartsObjc/Support/Marshallers.hh>



Charts::Touch TRChartsObjc::TouchStructMarshaller::marshall(const CodegenSupportObjc::StrongAnyPtr & in) const
{
	TRTouch * const tmp = (TRTouch*)in;
	Charts::Touch out;
	out.position = TRChartsObjc::getPointMarshaller().marshall([tmp position]);
	out.lastPosition = TRChartsObjc::getPointMarshaller().marshall([tmp lastPosition]);
	return out;
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::TouchStructMarshaller::unmarshall(const Charts::Touch & in) const
{
	TRTouch * out = [[TRTouch alloc] init];
	[out setPosition:TRChartsObjc::getPointMarshaller().unmarshall(in.position)];
	[out setLastPosition:TRChartsObjc::getPointMarshaller().unmarshall(in.lastPosition)];
	return out;
}


Charts::Touch TRChartsObjc::TouchStructMarshaller::marshallBoxed(const id & in) const
{
	return marshall(in);
}


id TRChartsObjc::TouchStructMarshaller::unmarshallBoxed(const Charts::Touch & in) const
{
	return unmarshall(in);
}

// TODO: temporary hack until we fix static init + threads problems properly

void TRChartsObjc::TouchStructMarshaller::init(void) const
{
}

