/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import <TRChartsObjc/Support/TransformStructMarshaller.hh>
#import <TRChartsObjc/Support/Marshallers.hh>



Charts::Transform TRChartsObjc::TransformStructMarshaller::marshall(const CodegenSupportObjc::StrongAnyPtr & in) const
{
	TRTransform * const tmp = (TRTransform*)in;
	Charts::Transform out;
	out.offset = TRChartsObjc::getPointMarshaller().marshall([tmp offset]);
	out.scale = TRChartsObjc::getPointMarshaller().marshall([tmp scale]);
	return out;
}


CodegenSupportObjc::StrongAnyPtr TRChartsObjc::TransformStructMarshaller::unmarshall(const Charts::Transform & in) const
{
	TRTransform * out = [[TRTransform alloc] init];
	[out setOffset:TRChartsObjc::getPointMarshaller().unmarshall(in.offset)];
	[out setScale:TRChartsObjc::getPointMarshaller().unmarshall(in.scale)];
	return out;
}


Charts::Transform TRChartsObjc::TransformStructMarshaller::marshallBoxed(const id & in) const
{
	return marshall(in);
}


id TRChartsObjc::TransformStructMarshaller::unmarshallBoxed(const Charts::Transform & in) const
{
	return unmarshall(in);
}

// TODO: temporary hack until we fix static init + threads problems properly

void TRChartsObjc::TransformStructMarshaller::init(void) const
{
}

