/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef TRChartsJNI_Support_AnimationEffectInterfaceMarshaller_cpp
#define TRChartsJNI_Support_AnimationEffectInterfaceMarshaller_cpp

#include <TRChartsJNI/Support/AnimationEffectInterfaceMarshaller.hpp>
#include <TRChartsJNI/Support/Marshallers.hpp>
#include <TRChartsJNI/Support/Handle.hpp>

#include <cassert>


bool TRChartsJNI::AnimationEffectInterfaceMarshaller::inited = false;


jclass TRChartsJNI::AnimationEffectInterfaceMarshaller::cls = nullptr;


jmethodID TRChartsJNI::AnimationEffectInterfaceMarshaller::midApply = nullptr;


class TRChartsJNI::AnimationEffectInterfaceMarshaller::Proxy : public Charts::AnimationEffect
{
public:
	Proxy(JNIEnv * env, const AnimationEffectInterfaceMarshaller & marshaller, jobject hostObject);

	virtual ~Proxy(void);

	jobject getHostObject(JNIEnv * env) const;

	virtual void apply(double position, double duration) const;

private:
	const AnimationEffectInterfaceMarshaller & marshaller;
	const jweak weakHostObject;
};



void TRChartsJNI::AnimationEffectInterfaceMarshaller::checkInited(JNIEnv * const env)
{
	if(!inited) {
		inited = true;
		cls = (jclass)env->NewGlobalRef(env->FindClass("com/thomsonreuters/corptech/charts/AnimationEffect"));
		midApply = env->GetMethodID(cls, "apply", "(DD)V");
	}
}


std::shared_ptr<Charts::AnimationEffect> TRChartsJNI::AnimationEffectInterfaceMarshaller::marshall(JNIEnv * const env, const jobject & in) const
{
	checkInited(env);
	if(in) {
		if(Utils::isBaseObjectInstance(env, in)) {
			Handle * const handle = reinterpret_cast<Handle *>(Utils::getBaseObjectHandle(env, in));
			return handle->getNativeObject<Charts::AnimationEffect>(env);
		} else {
			Proxy * const impl = new Proxy(env, *this, in);
			const jobject strongRef = env->NewGlobalRef(in);
			return std::shared_ptr<Charts::AnimationEffect>(impl, [=](Charts::AnimationEffect * const ptr) -> void {
				delete ptr;
				env->DeleteGlobalRef(strongRef);
			});
		}
	}
	return std::shared_ptr<Charts::AnimationEffect>();
}


jobject TRChartsJNI::AnimationEffectInterfaceMarshaller::unmarshall(JNIEnv * const env, const std::shared_ptr<Charts::AnimationEffect> & in) const
{
	checkInited(env);
	if(in) {
		CodegenSupport::BaseObject * const baseObject = dynamic_cast<CodegenSupport::BaseObject *>(in.get());
		if(baseObject) {
			Handle * const handle = reinterpret_cast<Handle *>(baseObject->getHandle());
			return handle->getHostObject(env);
		} else {
			Proxy * proxy = dynamic_cast<Proxy *>(in.get());
			if(proxy) {
				return proxy->getHostObject(env);
			} else {
				throw new std::logic_error("Cannot unmarshall");
			}
		}
	}
	return nullptr;
}



TRChartsJNI::AnimationEffectInterfaceMarshaller::Proxy::Proxy(JNIEnv * const env, const AnimationEffectInterfaceMarshaller & marshaller, const jobject hostObject)
	:marshaller(marshaller), weakHostObject(env->NewWeakGlobalRef(hostObject))
{
}


TRChartsJNI::AnimationEffectInterfaceMarshaller::Proxy::~Proxy(void)
{
	JNIEnv * const env = Utils::getThreadEnv();
	assert(env);
	env->DeleteWeakGlobalRef(weakHostObject);
}


jobject TRChartsJNI::AnimationEffectInterfaceMarshaller::Proxy::getHostObject(JNIEnv * const env) const
{
	return env->NewLocalRef(weakHostObject);
}


void TRChartsJNI::AnimationEffectInterfaceMarshaller::Proxy::apply(double position, double duration) const
{
	JNIEnv * const env = Utils::getThreadEnv();
	assert(env);
	checkInited(env);
	jvalue args[] = {
		TRChartsJNI::getNumberMarshaller().unmarshallToValue(env, position),
		TRChartsJNI::getNumberMarshaller().unmarshallToValue(env, duration)
	};
	const jobject hostObject = getHostObject(env);
	env->CallVoidMethodA(hostObject, midApply, args);
	env->DeleteLocalRef(hostObject);
}

#endif