/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef TRChartsJNI_Support_DateFormatterInterfaceMarshaller_hpp
#define TRChartsJNI_Support_DateFormatterInterfaceMarshaller_hpp

#include <TRChartsJNI/Support/BasicObjectMarshaller.hpp>
#include <TRCharts/DateFormatter.hpp>

namespace TRChartsJNI
{
	
	class DateFormatterInterfaceMarshaller : public BasicObjectMarshaller<std::shared_ptr<Charts::DateFormatter>, jobject>
	{
	public:
		virtual std::shared_ptr<Charts::DateFormatter> marshall(JNIEnv * env, const jobject & in) const;

		virtual jobject unmarshall(JNIEnv * env, const std::shared_ptr<Charts::DateFormatter> & in) const;

	private:

		static bool inited;
		static jclass cls;
		static jmethodID midFormatDate;

		static void checkInited(JNIEnv * env);

		class Proxy;
	};
}

#endif