/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef TRChartsJNI_Support_LineStyleSourceInterfaceMarshaller_cpp
#define TRChartsJNI_Support_LineStyleSourceInterfaceMarshaller_cpp

#include <TRChartsJNI/Support/LineStyleSourceInterfaceMarshaller.hpp>
#include <TRChartsJNI/Support/Marshallers.hpp>
#include <TRChartsJNI/Support/Handle.hpp>

#include <cassert>


bool TRChartsJNI::LineStyleSourceInterfaceMarshaller::inited = false;


jclass TRChartsJNI::LineStyleSourceInterfaceMarshaller::cls = nullptr;


jmethodID TRChartsJNI::LineStyleSourceInterfaceMarshaller::midGetLineStyles = nullptr;


class TRChartsJNI::LineStyleSourceInterfaceMarshaller::Proxy : public Charts::LineStyleSource
{
public:
	Proxy(JNIEnv * env, const LineStyleSourceInterfaceMarshaller & marshaller, jobject hostObject);

	virtual ~Proxy(void);

	jobject getHostObject(JNIEnv * env) const;

	virtual std::vector<Charts::LineStyle> getLineStyles(const std::shared_ptr<Charts::Series> & series, const Charts::IndexRange & range, const Charts::LineStyle & defaultLineStyle) const;

private:
	const LineStyleSourceInterfaceMarshaller & marshaller;
	const jweak weakHostObject;
};



void TRChartsJNI::LineStyleSourceInterfaceMarshaller::checkInited(JNIEnv * const env)
{
	if(!inited) {
		inited = true;
		cls = (jclass)env->NewGlobalRef(env->FindClass("com/thomsonreuters/corptech/charts/LineStyleSource"));
		midGetLineStyles = env->GetMethodID(cls, "getLineStyles", "(Lcom/thomsonreuters/corptech/charts/Series;Lcom/thomsonreuters/corptech/charts/IndexRange;Lcom/thomsonreuters/corptech/charts/LineStyle;)Ljava/util/List;");
	}
}


std::shared_ptr<Charts::LineStyleSource> TRChartsJNI::LineStyleSourceInterfaceMarshaller::marshall(JNIEnv * const env, const jobject & in) const
{
	checkInited(env);
	if(in) {
		if(Utils::isBaseObjectInstance(env, in)) {
			Handle * const handle = reinterpret_cast<Handle *>(Utils::getBaseObjectHandle(env, in));
			return handle->getNativeObject<Charts::LineStyleSource>(env);
		} else {
			Proxy * const impl = new Proxy(env, *this, in);
			const jobject strongRef = env->NewGlobalRef(in);
			return std::shared_ptr<Charts::LineStyleSource>(impl, [=](Charts::LineStyleSource * const ptr) -> void {
				delete ptr;
				env->DeleteGlobalRef(strongRef);
			});
		}
	}
	return std::shared_ptr<Charts::LineStyleSource>();
}


jobject TRChartsJNI::LineStyleSourceInterfaceMarshaller::unmarshall(JNIEnv * const env, const std::shared_ptr<Charts::LineStyleSource> & in) const
{
	checkInited(env);
	if(in) {
		CodegenSupport::BaseObject * const baseObject = dynamic_cast<CodegenSupport::BaseObject *>(in.get());
		if(baseObject) {
			Handle * const handle = reinterpret_cast<Handle *>(baseObject->getHandle());
			return handle->getHostObject(env);
		} else {
			Proxy * proxy = dynamic_cast<Proxy *>(in.get());
			if(proxy) {
				return proxy->getHostObject(env);
			} else {
				throw new std::logic_error("Cannot unmarshall");
			}
		}
	}
	return nullptr;
}



TRChartsJNI::LineStyleSourceInterfaceMarshaller::Proxy::Proxy(JNIEnv * const env, const LineStyleSourceInterfaceMarshaller & marshaller, const jobject hostObject)
	:marshaller(marshaller), weakHostObject(env->NewWeakGlobalRef(hostObject))
{
}


TRChartsJNI::LineStyleSourceInterfaceMarshaller::Proxy::~Proxy(void)
{
	JNIEnv * const env = Utils::getThreadEnv();
	assert(env);
	env->DeleteWeakGlobalRef(weakHostObject);
}


jobject TRChartsJNI::LineStyleSourceInterfaceMarshaller::Proxy::getHostObject(JNIEnv * const env) const
{
	return env->NewLocalRef(weakHostObject);
}


std::vector<Charts::LineStyle> TRChartsJNI::LineStyleSourceInterfaceMarshaller::Proxy::getLineStyles(const std::shared_ptr<Charts::Series> & series, const Charts::IndexRange & range, const Charts::LineStyle & defaultLineStyle) const
{
	JNIEnv * const env = Utils::getThreadEnv();
	assert(env);
	checkInited(env);
	jvalue args[] = {
		TRChartsJNI::getSeriesMarshaller().unmarshallToValue(env, series),
		TRChartsJNI::getIndexRangeMarshaller().unmarshallToValue(env, range),
		TRChartsJNI::getLineStyleMarshaller().unmarshallToValue(env, defaultLineStyle)
	};
	const jobject hostObject = getHostObject(env);
	const std::vector<Charts::LineStyle> result = TRChartsJNI::getListLineStyleMarshaller().callMethod(env, hostObject, midGetLineStyles, args);
	env->DeleteLocalRef(hostObject);
	return result;
}

#endif