/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#include <TRChartsJNI/Support/RangeStructMarshaller.hpp>
#include <TRChartsJNI/Support/Marshallers.hpp>

using namespace TRChartsJNI;
using namespace Charts;

namespace
{
	bool inited = false;
	jclass cls;
	jmethodID ctor;
	jfieldID fidMin;
	jfieldID fidMax;

	void checkInited(JNIEnv * const env)
	{
		if(!::inited) {
			::inited = true;
			::cls = (jclass)env->NewGlobalRef(env->FindClass("com/thomsonreuters/corptech/charts/Range"));
			::ctor = env->GetMethodID(::cls, "<init>", "()V");
			::fidMin = env->GetFieldID(cls, "min", "D");
			::fidMax = env->GetFieldID(cls, "max", "D");
		}
	}
}

Range RangeStructMarshaller::marshall(JNIEnv * const env, const jobject & in) const
{
	::checkInited(env);
	Range out;
	out.min = TRChartsJNI::getNumberMarshaller().getFieldValue(env, in, ::fidMin);
	out.max = TRChartsJNI::getNumberMarshaller().getFieldValue(env, in, ::fidMax);
	return out;
}

jobject RangeStructMarshaller::unmarshall(JNIEnv * const env, const Range & in) const
{
	::checkInited(env);
	jobject out = env->NewObject(::cls, ::ctor);
	TRChartsJNI::getNumberMarshaller().setFieldValue(env, out, ::fidMin, in.min);
	TRChartsJNI::getNumberMarshaller().setFieldValue(env, out, ::fidMax, in.max);
	return out;
}

Range RangeStructMarshaller::getFieldValue(JNIEnv * const env, const jobject obj, const jfieldID fieldID) const
{
	return marshall(env, env->GetObjectField(obj, fieldID));
}

void RangeStructMarshaller::setFieldValue(JNIEnv * const env, const jobject obj, const jfieldID fieldID, const Range & value) const
{
	env->SetObjectField(obj, fieldID, unmarshall(env, value));
}

Range RangeStructMarshaller::callMethod(JNIEnv * const env, const jobject obj, const jmethodID methodID, jvalue * const args) const
{
	return marshall(env, env->CallObjectMethodA(obj, methodID, args));
}