/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#include <TRChartsJNI/Support/TouchStructMarshaller.hpp>
#include <TRChartsJNI/Support/Marshallers.hpp>

using namespace TRChartsJNI;
using namespace Charts;

namespace
{
	bool inited = false;
	jclass cls;
	jmethodID ctor;
	jfieldID fidPosition;
	jfieldID fidLastPosition;

	void checkInited(JNIEnv * const env)
	{
		if(!::inited) {
			::inited = true;
			::cls = (jclass)env->NewGlobalRef(env->FindClass("com/thomsonreuters/corptech/charts/Touch"));
			::ctor = env->GetMethodID(::cls, "<init>", "()V");
			::fidPosition = env->GetFieldID(cls, "position", "Lcom/thomsonreuters/corptech/charts/Point;");
			::fidLastPosition = env->GetFieldID(cls, "lastPosition", "Lcom/thomsonreuters/corptech/charts/Point;");
		}
	}
}

Touch TouchStructMarshaller::marshall(JNIEnv * const env, const jobject & in) const
{
	::checkInited(env);
	Touch out;
	out.position = TRChartsJNI::getPointMarshaller().getFieldValue(env, in, ::fidPosition);
	out.lastPosition = TRChartsJNI::getPointMarshaller().getFieldValue(env, in, ::fidLastPosition);
	return out;
}

jobject TouchStructMarshaller::unmarshall(JNIEnv * const env, const Touch & in) const
{
	::checkInited(env);
	jobject out = env->NewObject(::cls, ::ctor);
	TRChartsJNI::getPointMarshaller().setFieldValue(env, out, ::fidPosition, in.position);
	TRChartsJNI::getPointMarshaller().setFieldValue(env, out, ::fidLastPosition, in.lastPosition);
	return out;
}

Touch TouchStructMarshaller::getFieldValue(JNIEnv * const env, const jobject obj, const jfieldID fieldID) const
{
	return marshall(env, env->GetObjectField(obj, fieldID));
}

void TouchStructMarshaller::setFieldValue(JNIEnv * const env, const jobject obj, const jfieldID fieldID, const Touch & value) const
{
	env->SetObjectField(obj, fieldID, unmarshall(env, value));
}

Touch TouchStructMarshaller::callMethod(JNIEnv * const env, const jobject obj, const jmethodID methodID, jvalue * const args) const
{
	return marshall(env, env->CallObjectMethodA(obj, methodID, args));
}