/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import "AbstractDateFormatterGeneratedTests.h"
#import <TRChartsObjc/AbstractDateFormatter.h>
#import "TestUtils.hh"

#import <XCTest/XCTestAssertions.h>

@implementation TRAbstractDateFormatterGeneratedTests

- (void)setUp
{
    [super setUp];
}

- (void)tearDown
{
    [super tearDown];
}

-(id)createInstance
{
	// class is abstract, tests will be run only in subclasses
	return nil;
}

- (void) testInitializeFieldSyntax
{
	TRAbstractDateFormatter * instance = [self createInstance];
	if(instance) {
		TRFormatSyntax expected = TR_FORMATSYNTAX_CSTDLIB;
		TRFormatSyntax actual = [instance syntax];
		XCTAssertEqual(expected, actual);
	}
}

- (void) testSetFieldSyntax
{
	TRAbstractDateFormatter * instance = [self createInstance];
	if(instance) {
		TRFormatSyntax original = [instance syntax];
		TRFormatSyntax expected = TRChartsObjc::getFormatSyntaxTestValue(original);
		[instance setSyntax:expected];
		TRFormatSyntax actual = [instance syntax];
		XCTAssertEqual(expected, actual);
	}
}


@end
