/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import "AnimationGeneratedTests.h"
#import <TRChartsObjc/Animation.h>
#import "TestUtils.hh"

#import <XCTest/XCTestAssertions.h>

@implementation TRAnimationGeneratedTests

- (void)setUp
{
    [super setUp];
}

- (void)tearDown
{
    [super tearDown];
}

-(id)createInstance
{
	return [[TRAnimation alloc] init];
}

- (void) testInitializeFieldDuration
{
	TRAnimation * instance = [self createInstance];
	if(instance) {
		double expected = 1.0;
		double actual = [instance duration];
		XCTAssertEqual(expected, actual);
	}
}

- (void) testInitializeFieldPosition
{
	TRAnimation * instance = [self createInstance];
	if(instance) {
		double expected = 0.0;
		double actual = [instance position];
		XCTAssertEqual(expected, actual);
	}
}

- (void) testInitializeFieldEffectList
{
	TRAnimation * instance = [self createInstance];
	if(instance) {
		NSArray * expected = @[];
		NSArray * actual = [instance effectList];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testInitializeFieldDelegate
{
	TRAnimation * instance = [self createInstance];
	if(instance) {
		id<TRAnimationDelegate> expected = nil;
		id<TRAnimationDelegate> actual = [instance delegate];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testSetFieldDuration
{
	TRAnimation * instance = [self createInstance];
	if(instance) {
		double original = [instance duration];
		double expected = TRChartsObjc::getNumberTestValue(original);
		[instance setDuration:expected];
		double actual = [instance duration];
		XCTAssertEqual(expected, actual);
	}
}

- (void) testSetFieldPosition
{
	TRAnimation * instance = [self createInstance];
	if(instance) {
		double original = [instance position];
		double expected = TRChartsObjc::getNumberTestValue(original);
		[instance setPosition:expected];
		double actual = [instance position];
		XCTAssertEqual(expected, actual);
	}
}

- (void) testSetFieldEffectList
{
	TRAnimation * instance = [self createInstance];
	if(instance) {
		NSArray * original = [instance effectList];
		NSArray * expected = TRChartsObjc::getListAnimationEffectTestValue(original);
		[instance setEffectList:expected];
		NSArray * actual = [instance effectList];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testSetFieldDelegate
{
	TRAnimation * instance = [self createInstance];
	if(instance) {
		id<TRAnimationDelegate> original = [instance delegate];
		id<TRAnimationDelegate> expected = TRChartsObjc::getAnimationDelegateTestValue(original);
		[instance setDelegate:expected];
		id<TRAnimationDelegate> actual = [instance delegate];
		XCTAssertEqualObjects(expected, actual);
	}
}


@end
