/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import "ConstraintGeneratedTests.h"
#import <TRChartsObjc/Constraint.h>
#import "TestUtils.hh"

#import <XCTest/XCTestAssertions.h>

@implementation TRConstraintGeneratedTests

- (void)setUp
{
    [super setUp];
}

- (void)tearDown
{
    [super tearDown];
}

-(id)createInstance
{
	return [[TRConstraint alloc] init];
}

- (void) testInitializeFieldBehaviour
{
	TRConstraint * instance = [self createInstance];
	if(instance) {
		id<TRConstraintBehaviour> expected = nil;
		id<TRConstraintBehaviour> actual = [instance behaviour];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testSetFieldBehaviour
{
	TRConstraint * instance = [self createInstance];
	if(instance) {
		id<TRConstraintBehaviour> original = [instance behaviour];
		id<TRConstraintBehaviour> expected = TRChartsObjc::getConstraintBehaviourTestValue(original);
		[instance setBehaviour:expected];
		id<TRConstraintBehaviour> actual = [instance behaviour];
		XCTAssertEqualObjects(expected, actual);
	}
}


@end
