/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#import "PointDecorationGeneratedTests.h"
#import <TRChartsObjc/PointDecoration.h>
#import "TestUtils.hh"

#import <XCTest/XCTestAssertions.h>

@implementation TRPointDecorationGeneratedTests

- (void)setUp
{
    [super setUp];
}

- (void)tearDown
{
    [super tearDown];
}

-(id)createInstance
{
	return [[TRPointDecoration alloc] init];
}

- (void) testInitializeFieldAbscissaAxis
{
	TRPointDecoration * instance = [self createInstance];
	if(instance) {
		TRContinuousAxis * expected = nil;
		TRContinuousAxis * actual = [instance abscissaAxis];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testInitializeFieldOrdinateAxis
{
	TRPointDecoration * instance = [self createInstance];
	if(instance) {
		TRContinuousAxis * expected = nil;
		TRContinuousAxis * actual = [instance ordinateAxis];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testInitializeFieldValue
{
	TRPointDecoration * instance = [self createInstance];
	if(instance) {
		TRCoordinates * expected = [TRCoordinates abscissa:0.0 ordinate:0.0];
		TRCoordinates * actual = [instance value];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testInitializeFieldPointStyle
{
	TRPointDecoration * instance = [self createInstance];
	if(instance) {
		TRPointStyle * expected = [TRPointStyle diameter:1.0];
		TRPointStyle * actual = [instance pointStyle];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testSetFieldAbscissaAxis
{
	TRPointDecoration * instance = [self createInstance];
	if(instance) {
		TRContinuousAxis * original = [instance abscissaAxis];
		TRContinuousAxis * expected = TRChartsObjc::getContinuousAxisTestValue(original);
		[instance setAbscissaAxis:expected];
		TRContinuousAxis * actual = [instance abscissaAxis];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testSetFieldOrdinateAxis
{
	TRPointDecoration * instance = [self createInstance];
	if(instance) {
		TRContinuousAxis * original = [instance ordinateAxis];
		TRContinuousAxis * expected = TRChartsObjc::getContinuousAxisTestValue(original);
		[instance setOrdinateAxis:expected];
		TRContinuousAxis * actual = [instance ordinateAxis];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testSetFieldValue
{
	TRPointDecoration * instance = [self createInstance];
	if(instance) {
		TRCoordinates * original = [instance value];
		TRCoordinates * expected = TRChartsObjc::getCoordinatesTestValue(original);
		[instance setValue:expected];
		TRCoordinates * actual = [instance value];
		XCTAssertEqualObjects(expected, actual);
	}
}

- (void) testSetFieldPointStyle
{
	TRPointDecoration * instance = [self createInstance];
	if(instance) {
		TRPointStyle * original = [instance pointStyle];
		TRPointStyle * expected = TRChartsObjc::getPointStyleTestValue(original);
		[instance setPointStyle:expected];
		TRPointStyle * actual = [instance pointStyle];
		XCTAssertEqualObjects(expected, actual);
	}
}


@end
