/*******************************************************************************
 * Copyright 2015 Thomson Reuters
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
/* NOTE: This file is autogenerated, do not edit this file directly.*/

#ifndef TRChartsJNI_Animation_hpp
#define TRChartsJNI_Animation_hpp

#include <TRChartsJNI/Support/Common.hpp>

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeCreate(JNIEnv *env, jobject obj);

JNIEXPORT void JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeDestroy(JNIEnv *env, jobject obj, jlong ptr);

JNIEXPORT jdouble JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeGetDuration(JNIEnv * env, jobject obj, jlong ptr);

JNIEXPORT void JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeSetDuration(JNIEnv * env, jobject obj, jlong ptr, jdouble value);

JNIEXPORT jdouble JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeGetPosition(JNIEnv * env, jobject obj, jlong ptr);

JNIEXPORT void JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeSetPosition(JNIEnv * env, jobject obj, jlong ptr, jdouble value);

JNIEXPORT jobject JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeGetEffectList(JNIEnv * env, jobject obj, jlong ptr);

JNIEXPORT void JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeSetEffectList(JNIEnv * env, jobject obj, jlong ptr, jobject value);

JNIEXPORT jobject JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeGetDelegate(JNIEnv * env, jobject obj, jlong ptr);

JNIEXPORT void JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeSetDelegate(JNIEnv * env, jobject obj, jlong ptr, jobject value);

JNIEXPORT void JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeRestart(JNIEnv * env, jobject obj, jlong ptr);

JNIEXPORT void JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeComplete(JNIEnv * env, jobject obj, jlong ptr);

JNIEXPORT void JNICALL Java_com_thomsonreuters_corptech_charts_Animation_nativeCancel(JNIEnv * env, jobject obj, jlong ptr);

#ifdef __cplusplus
}
#endif
#endif